version: "3.8"

networks:
  backend:
    name: backend

volumes:
  db:
  nextcloud:
  pihole_configs:
  dnsmasq_configs:
  nextcloud_apps:
  nextcloud_config:
  nextcloud_data:
  nextcloud_theme:

services:
  borgmatic:
    image: frutti93/borgmatic:latest
    container_name: borgmatic
    networks:
      - backend
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source:ro           # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository     # backup target
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/ # borgmatic config file(s) + crontab.txt
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg  # config and keyfiles
      - ${VOLUME_SSH}:/root/.ssh                  # ssh key for remote repositories
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg    # checksums used for deduplication
      - ${RCLONE_CONFIG}:/mnt/rclone_config       # Rclone config directory
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
      - RCLONE_TARGET=${RCLONE_TARGET}